"""基金阅读 Service 层入口。"""

from fund_agent.service.reading_service import (
    AggregateMultiYearAnnualPerformanceRequest,
    AggregateMultiYearAnnualPerformanceResult,
    AnnualExcessReturnExtraction,
    AnnualPerformanceFieldCitation,
    AnnualReportDocument,
    ExtractFeeRatesRequest,
    ExtractFeeRatesResult,
    ExtractAnnualExcessReturnRequest,
    ExtractAnnualExcessReturnResult,
    FeeRateExtraction,
    FundReadingService,
    ImportLocalReportRequest,
    ImportLocalReportResult,
    ListReportsRequest,
    ListReportsResult,
    MultiYearAnnualPerformanceRow,
    MultiYearAnnualPerformanceSeries,
    QueryRouteAttempt,
    ReadLocalReportRequest,
    ReadLocalReportResult,
)

__all__ = [
    "AggregateMultiYearAnnualPerformanceRequest",
    "AggregateMultiYearAnnualPerformanceResult",
    "AnnualExcessReturnExtraction",
    "AnnualPerformanceFieldCitation",
    "AnnualReportDocument",
    "ExtractAnnualExcessReturnRequest",
    "ExtractAnnualExcessReturnResult",
    "ExtractFeeRatesRequest",
    "ExtractFeeRatesResult",
    "FeeRateExtraction",
    "FundReadingService",
    "ImportLocalReportRequest",
    "ImportLocalReportResult",
    "ListReportsRequest",
    "ListReportsResult",
    "MultiYearAnnualPerformanceRow",
    "MultiYearAnnualPerformanceSeries",
    "QueryRouteAttempt",
    "ReadLocalReportRequest",
    "ReadLocalReportResult",
]
