"""基金阅读 Service 层入口。"""

from fund_agent.service.reading_service import (
    AggregateMultiYearAnnualPerformanceRequest,
    AggregateMultiYearAnnualPerformanceResult,
    AnnualExcessReturnExtraction,
    AnnualHoldingsResult,
    AnnualPerformanceFieldCitation,
    AnnualReportDocument,
    ExtractFeeRatesRequest,
    ExtractFeeRatesResult,
    ExtractAnnualExcessReturnRequest,
    ExtractAnnualExcessReturnResult,
    ExtractHoldingsRequest,
    ExtractHoldingsResult,
    FeeRateExtraction,
    FundReadingService,
    HoldingExtraction,
    ImportLocalReportRequest,
    ImportLocalReportResult,
    ListReportsRequest,
    ListReportsResult,
    MultiYearAnnualPerformanceRow,
    MultiYearAnnualPerformanceSeries,
    MultiYearHoldingsSeries,
    QueryRouteAttempt,
    ReadLocalReportRequest,
    ReadLocalReportResult,
)

__all__ = [
    "AggregateMultiYearAnnualPerformanceRequest",
    "AggregateMultiYearAnnualPerformanceResult",
    "AnnualExcessReturnExtraction",
    "AnnualHoldingsResult",
    "AnnualPerformanceFieldCitation",
    "AnnualReportDocument",
    "ExtractAnnualExcessReturnRequest",
    "ExtractAnnualExcessReturnResult",
    "ExtractFeeRatesRequest",
    "ExtractFeeRatesResult",
    "ExtractHoldingsRequest",
    "ExtractHoldingsResult",
    "FeeRateExtraction",
    "FundReadingService",
    "HoldingExtraction",
    "ImportLocalReportRequest",
    "ImportLocalReportResult",
    "ListReportsRequest",
    "ListReportsResult",
    "MultiYearAnnualPerformanceRow",
    "MultiYearAnnualPerformanceSeries",
    "MultiYearHoldingsSeries",
    "QueryRouteAttempt",
    "ReadLocalReportRequest",
    "ReadLocalReportResult",
]
